export const VIOLATION = {
  NAME_BLANK: 'NAME_BLANK',
  NAME_SIZE: 'NAME_SIZE',

  SURNAME_BLANK: 'SURNAME_BLANK',
  SURNAME_SIZE: 'SURNAME_SIZE',

  NICKNAME_BLANK: 'NICKNAME_BLANK',
  NICKNAME_SIZE: 'NICKNAME_SIZE',

  EMAIL_BLANK: 'EMAIL_BLANK',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_SIZE: 'EMAIL_SIZE',

  PASSWORD_BLANK: 'PASSWORD_BLANK',
  PASSWORD_SIZE: 'PASSWORD_SIZE',
} as const;